name: dart_printf
description: Very very simple format printing
version: 0.4.0
homepage: https://github.com/januwA/dart_printf

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.14.4
